added

diff --git a/azure/templates/post-deploy.yml b/azure/templates/post-deploy.yml
--- a/azure/templates/post-deploy.yml
+++ b/azure/templates/post-deploy.yml
@@ -118,6 +118,7 @@ steps:
       pyenv global 3.10.8
       python --version
     displayName: Set Python 3.10
+
   - bash: |
       set -e
       export RELEASE_RELEASEID=$(Build.BuildId)
@@ -167,20 +168,12 @@ steps:
         echo "Proxy test completed successfully as part of terraform resource up status check"
 
       else
-        echo "Running each test file with a 20-second delay"
-        
-        clear_dynamodb_script="clear_dynamodb.py"
-
-        # Find all test files and iterate over them one by one.
-        for test_file in $(find . -name "test_*.py"); do
-            echo "Running tests in file: $test_file"
-            echo "Waiting for 40 seconds to execute test cases..."
-            sleep 40
-            # Run the whole test file using unittest
-            $test_cmd -v -c "$test_file" || echo "Test in $test_file failed"
-            
-            echo "Waiting for 80 seconds before the next test..."
-            sleep 80
+        echo "running tests with 20 sec delay"
+        for test_case in $($test_cmd discover -s . -p "*.py" -v | grep "test_" | awk '{print $1}'); do
+          echo "Running test: $test_case"
+          $test_cmd -v -c $test_case || echo "Test $test_case failed"
+          echo "Waiting for 20 seconds before next test..."
+          sleep 20
         done
       fi
       echo "##vso[task.setvariable variable=TEST_FAILURE;]$test_status"
