VED-353: Wait for API to be available before running e2e tests. (#581)

diff --git a/azure/templates/post-deploy.yml b/azure/templates/post-deploy.yml
--- a/azure/templates/post-deploy.yml
+++ b/azure/templates/post-deploy.yml
@@ -80,38 +80,38 @@ steps:
 
   - bash: |
       set -ex
-      if ! [[ $APIGEE_ENVIRONMENT =~ .*-*sandbox ]]; then
-        counter=0
-        base_path="$SERVICE_BASE_PATH"
 
-        endpoint=""
-
-        if [[ $APIGEE_ENVIRONMENT =~ "prod" ]]; then
-          endpoint="https://api.service.nhs.uk/${base_path}/_status"
-        else
-          endpoint="https://${APIGEE_ENVIRONMENT}.api.service.nhs.uk/${base_path}/_status"
-        fi
-
-        while [[ $counter -lt 11 ]]; do
-          response=$(curl -H "apikey: $(status-endpoint-api-key)" -s "$endpoint")
-          response_code=$(jq -r '.checks.healthcheck.responseCode' <<< "$response")
-          response_body=$(jq -r '.checks.healthcheck.outcome' <<< "$response")
-          if [ "$response_code" -eq 200 ] && [ "$response_body" == "OK" ]; then
-              echo "Status test successful"
-              break
-          else
-              echo "Waiting for $endpoint to return a 200 response with 'OK' body..."
-              ((counter=counter+1)) # Increment counter by 1
-              echo "Attempt $counter"
-              sleep 30
-          fi
-        done
-        if [ $counter -eq 11 ]; then
-            echo "Status test failed: Maximum number of attempts reached"
-            exit 1
-        fi
+      endpoint=""
+      if [[ $APIGEE_ENVIRONMENT =~ "prod" ]]; then
+        endpoint="https://api.service.nhs.uk/${SERVICE_BASE_PATH}/_status"
+      else
+        endpoint="https://${APIGEE_ENVIRONMENT}.api.service.nhs.uk/${SERVICE_BASE_PATH}/_status"
       fi
-    displayName: Waiting for TF resources to be UP
+
+      counter=0
+      while [[ $counter -lt 31 ]]; do
+        response=$(curl -H "apikey: $(status-endpoint-api-key)" -s "$endpoint")
+        response_code=$(jq -r '.checks.healthcheck.responseCode' <<< "$response")
+        response_body=$(jq -r '.checks.healthcheck.outcome' <<< "$response")
+        status=$(jq -r '.status' <<< "$response")
+        if [ "$response_code" -eq 200 ] && [ "$response_body" == "OK" ] && [ "$status" == "pass" ]; then
+            echo "Status test successful"
+            break
+        else
+            echo "Waiting for $endpoint to return a 200 response with 'OK' body..."
+            ((counter=counter+1)) # Increment counter by 1
+            echo "Attempt $counter"
+            sleep 30
+        fi
+      done
+
+      if [ $counter -eq 31 ]; then
+          echo "Status test failed: Maximum number of attempts reached"
+          echo "Last response received:"
+          echo "$response"
+          exit 1
+      fi
+    displayName: Wait for API to be available
     workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)"
 
   - bash: |
@@ -164,7 +164,7 @@ steps:
         export DEFAULT_CLIENT_SECRET="$(INT_CLIENT_SECRET)"
         echo "running: $test_cmd -v -c test_deployment.py test_proxy.py"
         $test_cmd -v -c test_deployment.py test_proxy.py
-      
+
       elif [[ $APIGEE_ENVIRONMENT == "prod" ]]; then
         echo "Proxy test completed successfully as part of terraform resource up status check"
 
@@ -175,35 +175,35 @@ steps:
     workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e"
     displayName: Run Full Test Suite
 
-  
+
 
   - bash: |
       set -e
       if ! [[ "$APIGEE_ENVIRONMENT" == "prod" || "$APIGEE_ENVIRONMENT" == "int" || "$APIGEE_ENVIRONMENT" == *"sandbox" ]]; then
         echo "Running E2E batch folder test cases"
- 
+
         export AWS_PROFILE="apim-dev"
         aws_account_no="$(aws sts get-caller-identity --query Account --output text)"
         echo "Using AWS Account: $aws_account_no"
-        
+
         service_name="${FULLY_QUALIFIED_SERVICE_NAME}"
- 
+
         pr_no=$(echo "$service_name" | { grep -oE '[0-9]+$' || true; })
         if [ -z "$pr_no" ]; then
           workspace="$APIGEE_ENVIRONMENT"
         else
           workspace="pr-$pr_no"
         fi
- 
+
         poetry install --no-root  # Install dependencies defined in pyproject.toml
- 
+
         ENV="$workspace" poetry run python -m unittest -v -c
- 
+
         echo "E2E batch folder test cases executed successfully"
       else
         echo "Skipping E2E batch folder test cases as the environment is prod-int-sandbox"
       fi
- 
+
     displayName: Run full batch test suite
     workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e_batch"
     condition: eq(1, 2) # Disable task but make this step visible in the pipeline
