added

diff --git a/azure/templates/post-deploy.yml b/azure/templates/post-deploy.yml
--- a/azure/templates/post-deploy.yml
+++ b/azure/templates/post-deploy.yml
@@ -120,118 +120,89 @@ steps:
   - bash: |
       pyenv install -s 3.10.8
       pyenv global 3.10.8
-
       python --version
     displayName: Set Python 3.10
-    
-  # - bash: |
-  #     set -e 
-  #     if ! [[ "$APIGEE_ENVIRONMENT" == "ref" || "$APIGEE_ENVIRONMENT" == "prod" || "$APIGEE_ENVIRONMENT" == "int" || "$APIGEE_ENVIRONMENT" == *"sandbox" ]]; then
-  #       echo "Running E2E batch folder test cases"
-    
-  #       export AWS_PROFILE="apim-dev"
-  #       aws_account_no="$(aws sts get-caller-identity --query Account --output text)"
-        
-  #       service_name="${FULLY_QUALIFIED_SERVICE_NAME}"
 
-  #       pr_no=$(echo "$service_name" | { grep -oE '[0-9]+$' || true; })
-  #       if [ -z "$pr_no" ]; then
-  #         workspace="$APIGEE_ENVIRONMENT"
-  #       else
-  #         workspace="pr-$pr_no"
-  #       fi
+  - bash: |
+      set -e
+      export RELEASE_RELEASEID=$(Build.BuildId)
+      export SOURCE_COMMIT_ID=$(Build.SourceVersion)
+      export APIGEE_ENVIRONMENT="$(ENVIRONMENT)"
+      export APIGEE_USERNAME=apm-testing-internal-dev@nhs.net
+      export SERVICE_BASE_PATH="$(SERVICE_BASE_PATH)"
+      export APIGEE_ACCESS_TOKEN="$(secret.AccessToken)"
+      export PROXY_NAME="$(FULLY_QUALIFIED_SERVICE_NAME)"
+      export STATUS_API_KEY="$(status-endpoint-api-key)"
+      export AWS_DOMAIN_NAME="$(AWS_DOMAIN_NAME)"
+      export DYNAMODB_TABLE_NAME="$(DYNAMODB_TABLE_NAME)"
+      export IMMS_DELTA_TABLE_NAME="$(IMMS_DELTA_TABLE_NAME)"
+      export AWS_SQS_QUEUE_NAME="$(AWS_SQS_QUEUE_NAME)"
+      export AWS_SNS_TOPIC_NAME="$(AWS_SNS_TOPIC_NAME)"
+      export APIGEE_APP_ID=973b20ff-6e57-4248-b94f-200a18a03e37
+      echo "api key- $STATUS_API_KEY"
 
-  #       poetry install --no-root  # Install dependencies defined in pyproject.toml
+      export AWS_PROFILE=apim-dev
+      aws_account_no="$(aws sts get-caller-identity --query Account --output text)"
+      echo aws_account_no: $aws_account_no
 
-  #       ENV="$workspace" poetry run python -m unittest -v -c
+      poetry lock --no-update
+      poetry install
 
-  #       echo "E2E batch folder test cases executed successfully"
-  #     else
-  #       echo "Skipping E2E batch folder test cases as the environment is ref-prod-int-sandbox"
-  #     fi
+      test_cmd="poetry run python -m unittest"
+      $test_cmd -c -v -k test_deployment
 
-  #   displayName: Run full batch test suite
-  #   workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e_batch
+      if [[ $APIGEE_ENVIRONMENT =~ .*-*sandbox ]]; then
+        $test_cmd -c -v -k test_proxy.TestProxyHealthcheck -k test_deployment
 
-    - bash: |
-        set -e
+      elif [[ $APIGEE_ENVIRONMENT == "ref" ]]; then
+        $test_cmd -v -c test_deployment.py test_proxy.py
 
-        export RELEASE_RELEASEID=$(Build.BuildId)
-        export SOURCE_COMMIT_ID=$(Build.SourceVersion)
-        export APIGEE_ENVIRONMENT="$(ENVIRONMENT)"
-        export APIGEE_USERNAME=apm-testing-internal-dev@nhs.net
-        export SERVICE_BASE_PATH="$(SERVICE_BASE_PATH)"
-        export APIGEE_ACCESS_TOKEN="$(secret.AccessToken)"
-        export PROXY_NAME="$(FULLY_QUALIFIED_SERVICE_NAME)"
-        export STATUS_API_KEY="$(status-endpoint-api-key)"
-        export AWS_DOMAIN_NAME="$(AWS_DOMAIN_NAME)"
-        export DYNAMODB_TABLE_NAME="$(DYNAMODB_TABLE_NAME)"
-        export IMMS_DELTA_TABLE_NAME="$(IMMS_DELTA_TABLE_NAME)"
-        export AWS_SQS_QUEUE_NAME="$(AWS_SQS_QUEUE_NAME)"
-        export AWS_SNS_TOPIC_NAME="$(AWS_SNS_TOPIC_NAME)"
-        export APIGEE_APP_ID=973b20ff-6e57-4248-b94f-200a18a03e37
+      elif [[ $APIGEE_ENVIRONMENT == "int" ]]; then
+        export DEFAULT_CLIENT_ID="$(INT_CLIENT_ID)"
+        export DEFAULT_CLIENT_SECRET="$(INT_CLIENT_SECRET)"
+        $test_cmd -v -c test_deployment.py test_proxy.py
 
-        echo "api key- $STATUS_API_KEY"
+      elif [[ $APIGEE_ENVIRONMENT == "prod" ]]; then
+        echo "Proxy test completed successfully as part of terraform resource up status check"
 
-        export AWS_PROFILE=apim-dev
-        aws_account_no="$(aws sts get-caller-identity --query Account --output text)"
-        echo aws_account_no: $aws_account_no
+      else
+        echo "running tests with 20 sec delay"
+        for test_file in $(find . -name "test_*.py"); do
+          echo "Running tests in file: $test_file"
+          test_cases=$(python - <<END
+import unittest
+import sys
+loader = unittest.TestLoader()
+suite = loader.discover('.', pattern="$test_file")
+tests = []
+def get_tests(suite):
+    for test in suite:
+        if isinstance(test, unittest.TestSuite):
+            get_tests(test)
+        else:
+            tests.append(str(test))
+try:
+    get_tests(suite)
+    print('\n'.join(tests))
+except Exception as e:
+    print(f"Error while loading test cases: {e}", file=sys.stderr)
+    sys.exit(1)
+END
+          )
 
-        poetry lock --no-update
-        poetry install
+          if [ $? -ne 0 ]; then
+            echo "Error while extracting test cases for file: $test_file"
+            continue
+          fi
 
-        test_cmd="poetry run python -m unittest"
-
-        $test_cmd -c -v -k test_deployment
-
-        if [[ $APIGEE_ENVIRONMENT =~ .*-*sandbox ]]; then
-            $test_cmd -c -v -k test_proxy.TestProxyHealthcheck -k test_deployment
-
-        elif [[ $APIGEE_ENVIRONMENT == "ref" ]]; then
-            $test_cmd -v -c test_deployment.py test_proxy.py
-
-        elif [[ $APIGEE_ENVIRONMENT == "int" ]]; then
-            export DEFAULT_CLIENT_ID="$(INT_CLIENT_ID)"
-            export DEFAULT_CLIENT_SECRET="$(INT_CLIENT_SECRET)"
-            $test_cmd -v -c test_deployment.py test_proxy.py
-
-        elif [[ $APIGEE_ENVIRONMENT == "prod" ]]; then
-            echo "Proxy test completed successfully as part of terraform resource up status check"
-
-        else
-            for test_file in $(find . -name "test_*.py"); do
-                test_cases=$(python - <<END
-      import unittest
-      import sys
-
-      loader = unittest.TestLoader()
-      suite = loader.discover('.', pattern="$test_file")
-      tests = []
-
-      def get_tests(suite):
-          for test in suite:
-              if isinstance(test, unittest.TestSuite):
-                  get_tests(test)
-              else:
-                  tests.append(str(test))
-
-      try:
-          get_tests(suite)
-          print('\n'.join(tests))
-      except Exception as e:
-          print(f"Error while loading test cases: {e}", file=sys.stderr)
-          sys.exit(1)
-      END
-                )
-
-                for test_case in $test_cases; do
-                    echo "Running test: $test_case"
-                    $test_cmd -v -c $test_case || echo "Test $test_case failed"
-                    sleep 20
-                done
-            done
-        fi
-
+          for test_case in $test_cases; do
+            echo "Running test: $test_case"
+            $test_cmd -v -c $test_case || echo "Test $test_case failed"
+            echo "Waiting for 20 seconds before the next test..."
+            sleep 20
+          done
+        done
+      fi
     workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e"
     displayName: Run full test suite
 
