added

diff --git a/azure/templates/post-deploy.yml b/azure/templates/post-deploy.yml
--- a/azure/templates/post-deploy.yml
+++ b/azure/templates/post-deploy.yml
@@ -124,34 +124,34 @@ steps:
     displayName: Set Python 3.10
     
 
-  - bash: |
-      set -e 
-      if ! [[ "$APIGEE_ENVIRONMENT" == "ref" || "$APIGEE_ENVIRONMENT" == "prod" || "$APIGEE_ENVIRONMENT" == "int" || "$APIGEE_ENVIRONMENT" == *"sandbox" ]]; then
-        echo "Running E2E batch folder test cases"
+  # - bash: |
+  #     set -e 
+  #     if ! [[ "$APIGEE_ENVIRONMENT" == "ref" || "$APIGEE_ENVIRONMENT" == "prod" || "$APIGEE_ENVIRONMENT" == "int" || "$APIGEE_ENVIRONMENT" == *"sandbox" ]]; then
+  #       echo "Running E2E batch folder test cases"
     
-        export AWS_PROFILE="apim-dev"
-        aws_account_no="$(aws sts get-caller-identity --query Account --output text)"
+  #       export AWS_PROFILE="apim-dev"
+  #       aws_account_no="$(aws sts get-caller-identity --query Account --output text)"
         
-        service_name="${FULLY_QUALIFIED_SERVICE_NAME}"
+  #       service_name="${FULLY_QUALIFIED_SERVICE_NAME}"
 
-        pr_no=$(echo "$service_name" | { grep -oE '[0-9]+$' || true; })
-        if [ -z "$pr_no" ]; then
-          workspace="$APIGEE_ENVIRONMENT"
-        else
-          workspace="pr-$pr_no"
-        fi
+  #       pr_no=$(echo "$service_name" | { grep -oE '[0-9]+$' || true; })
+  #       if [ -z "$pr_no" ]; then
+  #         workspace="$APIGEE_ENVIRONMENT"
+  #       else
+  #         workspace="pr-$pr_no"
+  #       fi
 
-        poetry install --no-root  # Install dependencies defined in pyproject.toml
+  #       poetry install --no-root  # Install dependencies defined in pyproject.toml
 
-        ENV="$workspace" poetry run python -m unittest -v -c
+  #       ENV="$workspace" poetry run python -m unittest -v -c
 
-        echo "E2E batch folder test cases executed successfully"
-      else
-        echo "Skipping E2E batch folder test cases as the environment is ref-prod-int"
-      fi
+  #       echo "E2E batch folder test cases executed successfully"
+  #     else
+  #       echo "Skipping E2E batch folder test cases as the environment is ref-prod-int"
+  #     fi
 
-    displayName: Run full batch test suite
-    workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e_batch"
+  #   displayName: Run full batch test suite
+  #   workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e_batch"
    
 
   - bash: |
@@ -172,7 +172,7 @@ steps:
       export APIGEE_APP_ID=973b20ff-6e57-4248-b94f-200a18a03e37
       echo "api key- $STATUS_API_KEY"
 
-      #Exporting the same profile with which Terraform got deployed
+      # Exporting the same profile with which Terraform got deployed
       export AWS_PROFILE=apim-dev
       aws_account_no="$(aws sts get-caller-identity --query Account --output text)"
       echo aws_account_no: $aws_account_no
@@ -181,6 +181,7 @@ steps:
       poetry install
 
       test_cmd="poetry run python -m unittest"
+
       # Run test_deployment before doing anything. This will wait until deployment is ready
       $test_cmd -c -v -k test_deployment
 
@@ -198,13 +199,18 @@ steps:
         export DEFAULT_CLIENT_SECRET="$(INT_CLIENT_SECRET)"
         echo "running: $test_cmd -v -c test_deployment.py test_proxy.py"
         $test_cmd -v -c test_deployment.py test_proxy.py
-      
+
       elif [[ $APIGEE_ENVIRONMENT == "prod" ]]; then
         echo "Proxy test completed successfully as part of terraform resource up status check"
 
       else
-        echo "running: $test_cmd -v -c"
-        $test_cmd -v -c
+        echo "running tests with 20 sec delay"
+        for test_case in $($test_cmd discover -s . -p "*.py" -v | grep "test_" | awk '{print $1}'); do
+          echo "Running test: $test_case"
+          $test_cmd -v -c $test_case || echo "Test $test_case failed"
+          echo "Waiting for 20 seconds before next test..."
+          sleep 20
+        done
       fi
 
     workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e"
