added

diff --git a/azure/templates/post-deploy.yml b/azure/templates/post-deploy.yml
--- a/azure/templates/post-deploy.yml
+++ b/azure/templates/post-deploy.yml
@@ -166,17 +166,17 @@ steps:
         echo "Proxy test completed successfully as part of terraform resource up status check"
 
       else
-        echo "running tests with 20 sec delay"
+        echo "Running each test file with a 20-second delay"
+
+        # Find all test files and iterate over them one by one.
         for test_file in $(find . -name "test_*.py"); do
-          echo "Running tests in file: $test_file"
-          test_cases=$(python extract_test_cases.py "$test_file")
-          
-          for test_case in $test_cases; do
-              echo "Running test: $test_case"
-              $test_cmd -v -c $test_case || echo "Test $test_case failed"
-              echo "Waiting for 20 seconds before the next test..."
-              sleep 60
-          done
+            echo "Running tests in file: $test_file"
+            
+            # Run the whole test file using unittest
+            $test_cmd -v -c "$test_file" || echo "Test in $test_file failed"
+            
+            echo "Waiting for 20 seconds before the next test..."
+            sleep 20
       done
       fi
     workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e"
