updates

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -51,8 +51,7 @@ jobs:
         id: recordforwarder
         continue-on-error: true
         run: |
-          export PYTHONPATH=$PYTHONPATH:$(pwd)/backend
-          pip install poetry pydantic==1.10.13
+          PYTHONPATH=$(pwd)/backend:$(pwd)/backend/tests:$(pwd)/backend/src
           poetry run coverage run --source=backend/src -m unittest discover -s backend/tests -p "*batch*.py" || echo "recordforwarder tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage-recordforwarder-coverage.xml
 
@@ -78,7 +77,7 @@ jobs:
         continue-on-error: true
         run: |
           pip install poetry==1.8.4 moto==4.2.11 coverage redis botocore==1.35.49 simplejson responses structlog fhir.resources jsonpath_ng pydantic==1.10.13 requests aws-lambda-typing cffi pyjwt boto3-stubs-lite[dynamodb]~=1.26.90 python-stdnum==1.20
-          poetry run coverage run --source=backend -m unittest discover -s backend -p "*[!batch]*.py" || echo "fhir-api tests failed" >> failed_tests.txt
+          poetry run coverage run --source=backend -m unittest discover -s backend || echo "fhir-api tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage.xml
 
       - name: Run Test Failure Summary
